export const CHANNELS_REQUEST = 'CHANNELS_REQUEST';
export const CHANNELS_FAILURE = 'CHANNELS_FAILURE';
export const CHANNELS_SUCCESS = 'CHANNELS_SUCCESS';

export const MESSAGES_FETCH_REQUEST = 'MESSAGES_FETCH_REQUEST';
export const MESSAGES_FETCH_FAILURE = 'MESSAGES_FETCH_FAILURE';
export const MESSAGES_FETCH_SUCCESS = 'MESSAGES_FETCH_SUCCESS';

export const MESSAGES_SAVE_MESSAGE = 'MESSAGES_SAVE_MESSAGE';
export const MESSAGES_MESSAGE_STATUS_CHANGE = 'MESSAGES_MESSAGE_STATUS_CHANGE';

export const MESSAGE_EDIT = 'MESSAGE_EDIT';
export const MESSAGE_CHANGE = 'MESSAGE_CHANGE';
export const MESSAGE_DELETE_REQUEST= 'MESSAGE_DELETE_REQUEST';
export const MESSAGE_DELETE_SUCCESS= 'MESSAGE_DELETE_SUCCESS';

export const MESSAGE_SAVE_REQUEST = 'MESSAGE_SAVE_REQUEST';
export const MESSAGE_SAVE_FAILURE = 'MESSAGE_SAVE_FAILURE';
export const MESSAGE_SAVE_SUCCESS = 'MESSAGE_SAVE_SUCCESS';